/*
Certificate Management using Vault PKI API directly
This configuration uses Vault's native PKI secret backend API
to generate TLS certificates (not ACME).

Benefits:
- Direct API integration with Vault PKI
- No ACME protocol overhead
- Simpler for internal services
- No DNS/HTTP challenge required

Comparison with acme.tf:
- acme.tf: Uses ACME protocol (standardized, external account binding)
- cert_pki.tf: Uses Vault PKI API directly (simpler, internal only)

Note: Requires Vault PKI to be configured (see vault_pki.tf)
*/

# Random string for unique certificate naming
resource "random_string" "pki_cert_name" {
  length  = 4
  upper   = false
  lower   = true
  numeric = false
  special = false
}

/*
Generate private key for the certificate
This is used for the certificate signing request
*/
resource "tls_private_key" "pki_cert_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

/*
Request certificate from Vault PKI using native API
Uses the /pki_int/issue/<role> endpoint directly
*/
resource "vault_pki_secret_backend_cert" "app_cert" {
  backend = vault_mount.pki_int.path
  name    = vault_pki_secret_backend_role.intermediate_role.name

  # Certificate details
  common_name = "vault-api-${random_string.pki_cert_name.result}.${local.domain}"
  
  # Optional: Add alternative names
  # alt_names = ["app.${local.domain}", "service.${local.domain}"]
  # ip_sans   = ["10.0.0.1"]
  
  # TTL for the certificate (optional, defaults to role's max_ttl)
  ttl = "87600h" # 10 years in hours

  # Use auto-renew to handle certificate renewal
  auto_renew = true
  
  # Minimum seconds remaining before renewal
  min_seconds_remaining = 604800 # 7 days in seconds

  depends_on = [vault_pki_secret_backend_role.intermediate_role]
}

/*
Certificate data extraction from Vault PKI API response
Extract individual components for storage in AWS Secrets Manager
*/
locals {
  # Extract certificate components from Vault PKI response
  pki_cert        = vault_pki_secret_backend_cert.app_cert.certificate      # Public certificate
  pki_issuing_ca  = vault_pki_secret_backend_cert.app_cert.issuing_ca       # Issuing CA certificate
  pki_ca_chain    = vault_pki_secret_backend_cert.app_cert.ca_chain         # Full CA chain
  pki_private_key = vault_pki_secret_backend_cert.app_cert.private_key      # Private key
  pki_serial      = vault_pki_secret_backend_cert.app_cert.serial_number    # Serial number
  pki_expiration  = vault_pki_secret_backend_cert.app_cert.expiration       # Expiration timestamp
}

/*
TLS data formatted for easy consumption
Can be used in Kubernetes, Docker, or other services
*/
locals {
  pki_tls_data = {
    certificate    = local.pki_cert
    private_key    = local.pki_private_key
    ca_chain       = local.pki_ca_chain
    issuing_ca     = local.pki_issuing_ca
    serial_number  = local.pki_serial
    expiration     = local.pki_expiration
    common_name    = vault_pki_secret_backend_cert.app_cert.common_name
  }
}

/*
AWS Secrets Manager - Store Complete TLS Certificate Bundle
Store all certificate components in a single secret
*/
resource "aws_secretsmanager_secret" "vault_pki_cert_bundle" {
  name                    = "vault-pki-cert-bundle-${random_string.pki_cert_name.result}"
  description             = "TLS certificate bundle generated by Vault PKI API"
  recovery_window_in_days = 7

  tags = {
    Name         = "vault-pki-cert-bundle"
    Purpose      = "vault-pki-tls-bundle"
    ManagedBy    = "Terraform"
    CertType     = "vault-api"
    CommonName   = vault_pki_secret_backend_cert.app_cert.common_name
  }
}

resource "aws_secretsmanager_secret_version" "vault_pki_cert_bundle" {
  secret_id = aws_secretsmanager_secret.vault_pki_cert_bundle.id
  secret_string = jsonencode({
    certificate    = local.pki_cert
    private_key    = local.pki_private_key
    ca_chain       = local.pki_ca_chain
    issuing_ca     = local.pki_issuing_ca
    serial_number  = local.pki_serial
    common_name    = vault_pki_secret_backend_cert.app_cert.common_name
    expiration     = local.pki_expiration
    domain         = local.domain
    created_at     = timestamp()
  })

  depends_on = [vault_pki_secret_backend_cert.app_cert]
}

/*
AWS Secrets Manager - Store Certificate Only
Separate secret for just the public certificate
*/
resource "aws_secretsmanager_secret" "vault_pki_certificate" {
  name                    = "vault-pki-certificate-${local.region_sanitized}-${random_string.pki_cert_name.result}"
  description             = "TLS public certificate generated by Vault PKI API"
  recovery_window_in_days = 7

  tags = {
    Name         = "vault-pki-certificate"
    Purpose      = "vault-pki-tls-cert"
    ManagedBy    = "Terraform"
    CertType     = "vault-api"
  }
}

resource "aws_secretsmanager_secret_version" "vault_pki_certificate" {
  secret_id = aws_secretsmanager_secret.vault_pki_certificate.id
  secret_string = jsonencode({
    certificate   = local.pki_cert
    serial_number = local.pki_serial
    common_name   = vault_pki_secret_backend_cert.app_cert.common_name
    expiration    = local.pki_expiration
    domain        = local.domain
    created_at    = timestamp()
  })

  depends_on = [vault_pki_secret_backend_cert.app_cert]
}

/*
AWS Secrets Manager - Store Private Key
Separate secret for the private key with enhanced security
*/
resource "aws_secretsmanager_secret" "vault_pki_private_key" {
  name                    = "vault-pki-private-key-${local.region_sanitized}-${random_string.pki_cert_name.result}"
  description             = "TLS private key generated by Vault PKI API"
  recovery_window_in_days = 7

  tags = {
    Name         = "vault-pki-private-key"
    Purpose      = "vault-pki-tls-key"
    ManagedBy    = "Terraform"
    CertType     = "vault-api"
    Sensitive    = "true"
  }
}

resource "aws_secretsmanager_secret_version" "vault_pki_private_key" {
  secret_id = aws_secretsmanager_secret.vault_pki_private_key.id
  secret_string = jsonencode({
    private_key   = local.pki_private_key
    common_name   = vault_pki_secret_backend_cert.app_cert.common_name
    domain        = local.domain
    created_at    = timestamp()
  })

  depends_on = [vault_pki_secret_backend_cert.app_cert]
}

/*
AWS Secrets Manager - Store CA Chain
Separate secret for the CA certificate chain
*/
resource "aws_secretsmanager_secret" "vault_pki_ca_chain" {
  name                    = "vault-pki-ca-chain-${local.region_sanitized}-${random_string.pki_cert_name.result}"
  description             = "TLS CA certificate chain generated by Vault PKI API"
  recovery_window_in_days = 7

  tags = {
    Name         = "vault-pki-ca-chain"
    Purpose      = "vault-pki-tls-ca"
    ManagedBy    = "Terraform"
    CertType     = "vault-api"
  }
}

resource "aws_secretsmanager_secret_version" "vault_pki_ca_chain" {
  secret_id = aws_secretsmanager_secret.vault_pki_ca_chain.id
  secret_string = jsonencode({
    ca_chain      = local.pki_ca_chain
    issuing_ca    = local.pki_issuing_ca
    domain        = local.domain
    created_at    = timestamp()
  })

  depends_on = [vault_pki_secret_backend_cert.app_cert]
}

/*
Output certificate information for verification
*/
output "vault_pki_cert_info" {
  description = "Information about the Vault PKI generated certificate"
  value = {
    common_name   = vault_pki_secret_backend_cert.app_cert.common_name
    serial_number = vault_pki_secret_backend_cert.app_cert.serial_number
    expiration    = vault_pki_secret_backend_cert.app_cert.expiration
    secrets = {
      bundle      = aws_secretsmanager_secret.vault_pki_cert_bundle.name
      certificate = aws_secretsmanager_secret.vault_pki_certificate.name
      private_key = aws_secretsmanager_secret.vault_pki_private_key.name
      ca_chain    = aws_secretsmanager_secret.vault_pki_ca_chain.name
    }
  }
}
